version: '3'

volumes:
  mysql:

services:
  mariadb:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_USER: maki
      MYSQL_PASSWORD: maki
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: maki
    volumes:
      - mysql:/var/lib/mysql
  maki:
    image: maki
    build: .
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - .:/app
  admin_tool:
    image: admin_tool
    build:
      context: .
      dockerfile: Dockerfile.admin_tool
    depends_on:
      - mariadb
    ports:
      - '3001:3000'
    volumes:
      - ./admin_tool/.:/app
