version: '3'

volumes:
  mysql: {}

services:
  mariadb:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: api_server
    ports:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql

  kotori:
    image: api_server
    build: .
    depends_on:
      - mariadb
    environment:
      DATABASE_URL: mysql2://root:pass@mariadb/api_server
    volumes:
      - .:/app
