version: '3'

volumes:
  mysql:

services:
  mariadb:
    image: maki_database
    build:
      context: ./maki_database
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
  maki:
    image: maki
    build: .
    env_file: .env
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - .:/app
  admin_tool:
    image: admin_tool
    build:
      context: .
      dockerfile: Dockerfile.admin_tool
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - '4001:3000'
    volumes:
      - ./admin_tool/.:/app
