version: '3'

volumes:
  mysql:

services:
  mariadb:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    env_file: .env
    ports:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
  maki:
    image: maki
    build: .
    env_file: .env
    volumes:
      - .:/app
